### ISSUE TITLE
Problems installing gr-gsm

### ISSUE THREAD

**Issue by cspencer49519** [nejohnson2/homebrew-sdr#4]
Hello, trying to install gr-gsm and running into an iissue.

==> make install
Last 15 lines from /Users/graffix/Library/Logs/Homebrew/gr-gsm/02.make:
cd /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx && /usr/local/bin/python2 -O /tmp/gr-gsm-20200412-4363-1u06ru5/build/python_compile_helper.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/__init__.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/udp_link.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/ctrl_if.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/ctrl_if_bb.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/radio_if.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/radio_if_uhd.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/radio_if_lms.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/radio_if_grc.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/transceiver.py /tmp/gr-gsm-20200412-4363-1u06ru5/python/trx/dict_toggle_sign.py /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/__init__.pyo /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/udp_link.pyo /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/ctrl_if.pyo /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/ctrl_if_bb.pyo /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/radio_if.pyo /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/radio_if_uhd.pyo /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/radio_if_lms.pyo /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/radio_if_grc.pyo /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/transceiver.pyo /tmp/gr-gsm-20200412-4363-1u06ru5/build/python/trx/dict_toggle_sign.pyo
[ 89%] Built target pygen_python_trx_5bdbf
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f apps/CMakeFiles/pygen_apps.dir/build.make apps/CMakeFiles/pygen_apps.dir/depend
cd /tmp/gr-gsm-20200412-4363-1u06ru5/build && /usr/local/Cellar/cmake/3.17.0_1/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/gr-gsm-20200412-4363-1u06ru5 /tmp/gr-gsm-20200412-4363-1u06ru5/apps /tmp/gr-gsm-20200412-4363-1u06ru5/build /tmp/gr-gsm-20200412-4363-1u06ru5/build/apps /tmp/gr-gsm-20200412-4363-1u06ru5/build/apps/CMakeFiles/pygen_apps.dir/DependInfo.cmake --color=
Scanning dependencies of target pygen_apps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f apps/CMakeFiles/pygen_apps.dir/build.make apps/CMakeFiles/pygen_apps.dir/build
[ 90%] Generating grgsm_livemon
cd /tmp/gr-gsm-20200412-4363-1u06ru5/build/apps && /usr/local/Cellar/cmake/3.17.0_1/bin/cmake -E env PYTHONPATH="/tmp/gr-gsm-20200412-4363-1u06ru5/python:/tmp/gr-gsm-20200412-4363-1u06ru5/python/misc_utils:/tmp/gr-gsm-20200412-4363-1u06ru5/python/demapping:/tmp/gr-gsm-20200412-4363-1u06ru5/python/receiver:/tmp/gr-gsm-20200412-4363-1u06ru5/python/transmitter:/tmp/gr-gsm-20200412-4363-1u06ru5/python/trx:/tmp/gr-gsm-20200412-4363-1u06ru5/build/swig" GRC_BLOCKS_PATH=/tmp/gr-gsm-20200412-4363-1u06ru5/grc /usr/local/Cellar/gnuradio/3.7.13.4_14/bin/grcc -d /tmp/gr-gsm-20200412-4363-1u06ru5/build/apps /tmp/gr-gsm-20200412-4363-1u06ru5/apps/grgsm_livemon.grc
Traceback (most recent call last):
  File "/usr/local/Cellar/gnuradio/3.7.13.4_14/libexec/bin/grcc", line 34, in <module>
    from gnuradio.grc.core.Platform import Platform
ImportError: No module named grc.core.Platform
make[2]: *** [apps/grgsm_livemon] Error 1
make[1]: *** [apps/CMakeFiles/pygen_apps.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/nejohnson2/homebrew-sdr/issues

These open issues may also help:
Can't install gr-gsm https://github.com/nejohnson2/homebrew-sdr/issues/3
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.

**Comment by supashot** [comment]
"File "/usr/local/Cellar/gnuradio/3.7.13.4_14/libexec/bin/grcc", line 34, in 
from gnuradio.grc.core.Platform import Platform
ImportError: No module named grc.core.Platform"

Did you install gnuradio and grc?
